### ISSUE TITLE
Should default to HTTPS for your site URL

### ISSUE THREAD

**Issue by nogweii** [drjekyllthemes/drjekyllthemes.github.io#1]
Edit `_config.yaml` to use https rather than http in the URL. Otherwise, when accessing https://drjekyllthemes.github.io/ Firefox and Chrome will block loading the stylesheets, making the gallery look fairly plain:

![drjekyllthemes_https_no_css](https://cloud.githubusercontent.com/assets/14547/8738882/ce15935a-2be9-11e5-8f21-2d7fc743d007.png)

**Comment by geraldb** [comment]
Thanks. Will see what I can do. Maybe use a relative path for the style sheet.

**Comment by gynter** [comment]
Use `//`: http://stackoverflow.com/questions/4659345/is-there-any-downside-for-using-a-leading-double-slash-to-inherit-the-protocol-in

**Comment by geraldb** [comment]
Good point. Thanks for the link and the //: option. Tried it - looks like it's working. Cheers.

**Comment by geraldb** [comment]
FYI: I've added a new the site.path setting/variable for using the absolute path (w/o host). Looks it's working now for both http and https w/o any "tricks" e.g. using //:. Cheers.
