### ISSUE TITLE
Multiple comments

### ISSUE THREAD

**Issue by jacobtomlinson** [drjekyllthemes/drjekyllthemes.github.io#5]
Just a friendly note to say your multiple comments on the Jekyll Themes repo are getting a little spammy, my timeline is full of them. One comment is probably enough for each PR.

A slight sidenote, when thinking about setting up my own fork of Jekyll Themes one reason I was going to keep it the same format was the fact that I could merge in PRs from Jekyll Themes without people having to raise a new PR against my repo in a different format. They shouldn't have to re-do their work just because the owner of Jekyll Theme isn't looking after his project properly.

**Comment by geraldb** [comment]
Thanks for the update. Again a friendly reminder please send your comments to the jekyll talk forum. Cheers.
